#Configurar ~~~
#Siga os dois passoas abaixo para configurar seu site

#Passo 1.1: Mude SeuNomeDeUsuario para o nome de usuário do GitHub:
user: gabano

#Passo 1.2: Dê um nome ao seu grupo de estudos.
title: GER NUPEM/UFRJ

description: "Grupo de estudos em R NUPEM/UFRJ"

#Passo 2: Clique no botão verde ('Commit Changes') no fim dessa página.

# É isso, seu sítio está configurado!
# Você pode vê-lo em https://YourUserName.github.io/studyGroup/
# Não é preciso mudar nada abaixo dessa linha.
# Para criar seu primeiro evento, confira as intruções em https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Enfrentando problemas? Abra uma nova Issue em https://github.com/mozillascience/studyGroup/issues e nós o ajudaremos assim que possível!

# Configuração opcional
# Nada disso precisa ser mudado - mas sinta-se livre!

titleBackground: "https://s3-us-west-2.amazonaws.com/webmaker-kits/learning%402x.jpg"
headlineSmall: "Bem-vindo ao nosso Grupo de Estudos"
headlineMain: "Vamos trabalhar juntos"

# Configurar Google Calendar
# Uso:
# 1. crie uma nova conta do google
# 2. mude 'USUARIO' nos endereços de exemplo abaixo para o nome da nova conta do google onde você criou o calendário
# 3. mude calendar_on para TRUE.

calendar_on: FALSE
calendar_embed_url: "https://www.google.com/calendar/embed?src=USUARIO@gmail.com"
calendar_ical_url: "https://www.google.com/calendar/ical/USUARIO@gmail.com/public/basic.ics"



#========================================
# Não toque em nada abaixo dessa linha :)
#========================================
# Configurações de cor (hex-codes sem o jogo da velha)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Configurações da edição (build)
markdown: kramdown
permalink: pretty

