#Setup ~~~
#Follow these 2 steps to set up your site.

#Step 1: change YourUserName to the user name you chose on GitHub:
user: gabano

#Step 2: give your study group a name and a short description:
title: GER NUPEM/UFRJ

description: "Grupo de estudos em R NUPEM/UFRJ"

#Step 2: press the green 'Commit Changes' button at the bottom of this page.

# That's it, your website is all set up!
# You can see it at https://YourUserName.github.io/studyGroup/
# No need to change anything below this line.
# To make your first event, check out the instructions at https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Having trouble? Open a new issue at https://github.com/mozillascience/studyGroup/issues and we'll help you out ASAP!

# Optional Configuration
# None of these things need to be changed - but feel free!

titleBackground:Bem-vindo ao nosso Grupo de Estudos"
headlineMain: "Vamos trabalhar juntos"

# Setup Google Calendar
# Usage:
# 1. create a new google account
# 2. change 'USER' in the example urls below to the username of the google account you made for your calendar
# 3. set calendar_on: True.

calendar_on: TRUE



#========================================
# No touching anything below this line :)
#========================================
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty

